### PR TITLE
Updates for SplitRow to work with Swift 5 & Eureka 5.0.0

### PR DESCRIPTION
**Pull request by kamerc**
Changes for Carthage

### CODE REVIEW

**Comment by kamerc** [comment]
@marbetschar can you verify this looks correct? I don't use Carthage personally so I wanted you to take a look before I push and create a release.

**Comment by marbetschar** [comment]
@kamerc will test as soon as I‘m back home. Will take some hours though.

**Comment by marbetschar** [comment]
Awesome job! One tiny thing: According to their [CHANGELOG](https://github.com/xmartlabs/Eureka/blob/master/CHANGELOG.md) Eureka v5 requires iOS 9.3 and Xcode 10.0 - not iOS 10.0 We should also adhere to this, therefore the build target for SplitRow should be the same as for Eureka (= 9.3).

Feel free to merge and release as soon as you changed the build target version! 🎉🥳🎉

**Comment by marbetschar** [comment]
🎉🎉🎉 Thank you so much!!! 🙏🏼🙏🏼

**Comment by kamerc** [comment]
@marbetschar FYI that I created the 2.0.0 version on GitHub and am currently working on trying to push the podspec update to cocopods but dealing with errors related to simulators: - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: com.apple.coresimulator.simruntime.ios-12-2, com.apple.coresimulator.simruntime.tvos-12-2, com.apple.coresimulator.simruntime.watchos-5-2). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

I am about to step away from my desk so I will look back at it in a few hours.

**Comment by kamerc** [comment]
@marbetschar I finally figured out the issue and tried to push the PodSpec but got this error: [!] You (kate.mercer@sas.com) are not allowed to push new versions for this pod. The owners of this pod are marco@mandelkind.swiss and email@marco.betschart.name.

are you able to add me?

**Comment by marbetschar** [comment]
@kamerc good catch! Sure, hold on a sec

**Comment by marbetschar** [comment]
Done:

```
$ pod trunk add-owner SplitRow kate.mercer@sas.com
  - Owners:
    - Marco Betschart <marco@mandelkind.swiss>
    - Marco Betschart <email@marco.betschart.name>
    - Kate Mercer <kate.mercer@sas.com>
```

**Comment by kamerc** [comment]
thanks, version 2.0.0 has been pushed. I am now using it in my codebase.

**Pull request merged**
