### PR TITLE
Create Package.swift

### PR DESCRIPTION
**Pull request by jimisaacs**
This is currently not ready to merge, as it depends on a fork of Eureka. When/if xmartlabs/Eureka#1976 gets merged. I'll update this.

### CODE REVIEW

**Comment by jimisaacs** [comment]
Well xmartlabs/Eureka#1976 was merged, thanks @mats-claassen
 
I've updated back to mainline repo, but still not ready for merge, as I think it needs a proper version of Eureka. Currently have it locked to a git revision.

**Comment by AndrewBennet** [comment]
@jimisaacs did you manage to get this working?

I ask because I am trying to get [EurekaCommunity/ImageRow](https://github.com/EurekaCommunity/ImageRow) working with Swift Package Manager too, and I hit an issue where the build of the Eureka dependency fails with error `no such module 'UIKit'`:

```
/Users/andrew/code/ImageRow/.build/checkouts/Eureka/Source/Core/BaseRow.swift:26:8: error: no such module 'UIKit'
import UIKit
       ^
```

I see some commits in this pull request where you've added `import UIKit` to various files -- looks like you may have hit a similar problem. Am I right?

A Swift Package Manager-supporting version of Eureka has now been released (5.2.0) so it would be good to get these additional libraries supported too (if possible).

**Comment by jimisaacs** [comment]
@AndrewBennet it's not a "problem" per se, it's just that how the library builds is updated where it doesn't auto import iOS specific libraries. You have to import them, including Foundation.

**Comment by jimisaacs** [comment]
@AndrewBennet I'm guessing your particular problem is related to target platform(s). Make sure you build for iOS, such as `platforms: [.iOS(.v9)]` for example. Without it, it will build for MacOS, where there is no UIKit.

**Comment by jimisaacs** [comment]
Looks like @funkenstrahlen figured it out ;) https://github.com/EurekaCommunity/ImageRow/pull/81

**Comment by AndrewBennet** [comment]
Ah great! I didn't notice that pull request - thanks for pointing me in that direction :)

**Comment by jimisaacs** [comment]
This should be ready now, please review.

**Comment by patburns** [comment]
Plus one on the review. We'd like to move this to SPM as well .

**Comment by marbetschar** [comment]
thank you guys for the SPM addition! just merged it into master.

@kamerc any chance you can create a new `2.2` release? Unfortunately I don't have access to any macOS momentarily.

**Pull request merged**
