### PR TITLE
Updates for SplitRow to work with Swift 5 & Eureka 5.0.0

### PR DESCRIPTION
**Pull request by kamerc**
Note: Eureka 5 required that the minimum ios platform be increased
Also updated podspec. Repo owner will need to increase release version & push release

### CODE REVIEW

**Comment by marbetschar** [comment]
@kamerc awesome, thank you so much for the work you put in SplitRow! What do you think about adding you as repo owner? This way we can simplify and speed up things on your end.

And from my point of view: I'm not that much into iOS development currently - therefore I'm not as responsive as I should be for a project such as SplitRow. And the longer I'm apart, the harder it gets to catch up.

**Comment by kamerc** [comment]
@marbetschar can there be more than one owner? I don't want to necessarily take on all responsibility of the whole project and all incoming pull requests, etc.

**Comment by marbetschar** [comment]
Sure!

Don't worry, I'm still available to take on incoming stuff from time to time - so we can perfectly share the load. It's not too much anyways.

I'm mainly concerned to keep the SplitRow project alive in the long run as it seems I'll be slowly drifting away from mainly iOS development.

**Comment by marbetschar** [comment]
@kamerc just added you as repo admin. Feel free to merge your pull request. I'd suggest we go for a major release with this (2.0.0). What do you think?

**Comment by kamerc** [comment]
@marbetschar sorry for the delay, I was out of the office Friday-Monday. I agree on a major release in this case. Would you like me to try doing it and see if I am able to?

**Comment by marbetschar** [comment]
@kamerc if you have time, this would be awesome! I won't make it this week probably. And basically I was only capable in doing a release thanks to your Cocoapods instructions back then ;)

As for Carthage it basically is enough to just tag the master branch (aka. creating a new Release on GitHub).

**Pull request merged**
