### PR TITLE
Update to Eureka 5.1.0 since the iOS13 dark mode changes are now in p…

### PR DESCRIPTION
**Pull request by kamerc**
…roduction

### CODE REVIEW

**Comment by leafarenuk** [comment]
Hey @kamerc / @marbetschar could you please merge this PR so that we can use the dark mode with this great extension? Can I help with something?

**Comment by marbetschar** [comment]
From your point of view @kamerc is there anything left to do in this PR apart from updating Carthage dependency to Eureka 5.1?

**Comment by kamerc** [comment]
@marbetschar nothing else left to do besides Carthage

**Comment by marbetschar** [comment]
@kamerc awesome!! Will merge, update & create a new release then

**Comment by marbetschar** [comment]
@leafarenuk the release is ready (2.1.0). Feel free to open a new issue if you experience any errors.

**Pull request merged**
